[profile.default]
src = 'src'
out = 'foundry-out'
solc_version = '0.8.24'
libs = ["lib"]
evm_version = 'cancun'
ffi = true
fs_permissions = [
    { access = "read", path = "./script/config" },
]
optimizer = true
optimizer_runs = 200

[etherscan]
bsc-testnet = { key = "5D7WU9RKFU6BNK6UH117JM6X6BVU36H76C" }
